#!/usr/bin/env perl

use warnings;
use strict;
use Pod::Usage;

unless (@ARGV == 0) {
    pod2usage({ -verbose => 2 }) if $ARGV[0] eq "--help"
                                 or $ARGV[0] eq "-h";
}

use JSON::XS;

die if not defined $ARGV[0];

my @workspaces = map
                   {$_->{name}}
                   @{decode_json `i3-msg -t get_workspaces`};

my $nth_workspace = $workspaces[$ARGV[0]-1];

die if not defined $nth_workspace;

print $nth_workspace . "\n";

if (defined $ARGV[1] && $ARGV[1] eq "--switch") {
    exec("i3-msg 'workspace \"$nth_workspace\"'")
}

=head1 NAME

i3-nth-ws - focus nth workspace

=head1 SYNOPSIS

B<i3-nth-ws> I<n> [I<--switch>]

=head1 DESCRIPTION

Print to stdout the name of the I<n>th workspace, regardless of its name. If
given I<--switch>, actually focus that workspace.

=head1 SEE ALSO

B<i3>(1)

=head1 COPYRIGHT

Copyright (C) 2012  Wojciech Siewierski

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
