#!/bin/sh

# Run within a stack container with two windows, with the lower one focused.
#
# Creates a large tabbed container with the first window in it and a small
# vertically-split container below with the previously focused one.
#
#
#
#   +---------------------------------+
#   |1,2 stacked                      |
#   |                                 |
#   |                                 |
#   |                                 |
#   |                2                |
#   |                                 |
#   |                                 |
#   |                                 |
#   |                                 |
#   +---------------------------------+
#                    |
#                    |
#                    | i3-programming
#                    |
#                    |
#                    v
#   +---------------------------------+
#   |1 tabbed                         |
#   |                                 |
#   |                1                |
#   |                                 |
#   |                                 |
#   +---------------------------------+
#   |2 vertical                       |
#   |                2                |
#   |                                 |
#   +---------------------------------+
#                    |
#                    |
#                    | some new windows
#                    |
#                    |
#                    v
#   +---------------------------------+
#   |1,3 tabbed                       |
#   |                                 |
#   |                1                |
#   |                                 |
#   |                                 |
#   +----------------+----------------+
#   |2,4 vertical    |                |
#   |       2        |       4        |
#   |                |                |
#   +----------------+----------------+

i3-msg 'focus up                             ;
        split v                              ;
        focus down                           ;
        move up                              ;
        resize shrink height 60 px or 15 ppt ;
        split h                              ;
        focus up                             ;
        split h                              ;
        layout tabbed                        ;
        focus down' > /dev/null
